<?xml version="1.0" encoding="UTF-8"?>
<!-- You may freely edit this file. See commented blocks below for -->
<!-- some examples of how to customize the build. -->
<!-- For example, you can choose to override the "-init-user" target to -->
<!-- customize the values of the project properties, for example set a -->
<!-- different value for "user.properties.file". -->
<project name="swp391_booking" default="default" basedir=".">
    <description>Builds, tests, and runs the project swp391_booking.</description>
    <!-- Fallback j2ee.server.home if not set in nbproject/private/private.properties -->
    <property name="j2ee.server.home" value="C:/Program Files/Apache Software Foundation/Tomcat 10.1"/>
    <import file="nbproject/build-impl.xml"/>
</project>

